CREATE TABLE ALLOCATAIRES (
    NUMERO BIGSERIAL PRIMARY KEY,
    NO_AVS VARCHAR(200) UNIQUE,
    PRENOM    VARCHAR(200) NOT NULL,
    NOM    VARCHAR(200) NOT NULL
);

CREATE TABLE ALLOCATIONS (
    NUMERO BIGSERIAL PRIMARY KEY,
    MONTANT NUMERIC(9,2) NOT NULL,
    CANTON VARCHAR(2) NOT NULL,
    DEBUT DATE NOT NULL,
    FIN DATE
);

ALTER TABLE ALLOCATIONS ADD CONSTRAINT UK_ALLOCATIONS UNIQUE (CANTON,FIN);

CREATE TABLE ENFANTS (
    NUMERO BIGSERIAL PRIMARY KEY,
    NO_AVS VARCHAR(200) UNIQUE,
    PRENOM    VARCHAR(200) NOT NULL,
    NOM    VARCHAR(200) NOT NULL
);

CREATE TABLE VERSEMENTS (
    NUMERO BIGSERIAL PRIMARY KEY NOT NULL,
    FK_ALLOCATAIRES BIGINT NOT NULL,
    DATE_VERSEMENT    DATE NOT NULL,
    MOIS_VERSEMENT    DATE NOT NULL
);

ALTER TABLE VERSEMENTS ADD CONSTRAINT FK_VERSEMENTS1 FOREIGN KEY (FK_ALLOCATAIRES) REFERENCES ALLOCATAIRES(NUMERO);


CREATE TABLE ALLOCATIONS_ENFANTS (
     NUMERO BIGSERIAL PRIMARY KEY,
     FK_ENFANTS BIGINT NOT NULL,
     FK_ALLOCATIONS    BIGINT NOT NULL
);

ALTER TABLE ALLOCATIONS_ENFANTS ADD CONSTRAINT FK_ALLOCATIONS_ENFANTS1 FOREIGN KEY (FK_ENFANTS) REFERENCES ENFANTS(NUMERO);
ALTER TABLE ALLOCATIONS_ENFANTS ADD CONSTRAINT FK_ALLOCATIONS_ENFANTS2 FOREIGN KEY (FK_ALLOCATIONS) REFERENCES ALLOCATIONS(NUMERO);

CREATE TABLE VERSEMENTS_ALLOCATIONS (
    NUMERO BIGSERIAL PRIMARY KEY,
    FK_VERSEMENTS BIGINT NOT NULL,
    FK_ALLOCATIONS_ENFANTS BIGINT NOT NULL
);

ALTER TABLE VERSEMENTS_ALLOCATIONS ADD CONSTRAINT FK_VERSEMENTS_ALLOCATIONS1 FOREIGN KEY (FK_VERSEMENTS) REFERENCES VERSEMENTS(NUMERO);
ALTER TABLE VERSEMENTS_ALLOCATIONS ADD CONSTRAINT FK_VERSEMENTS_ALLOCATIONS2 FOREIGN KEY (FK_ALLOCATIONS_ENFANTS) REFERENCES ALLOCATIONS_ENFANTS(NUMERO);

CREATE TABLE ALLOCATIONS_NAISSANCE (
                                       NUMERO BIGSERIAL PRIMARY KEY,
                                       FK_ENFANTS BIGINT,
                                       MONTANT    NUMERIC(9,2)
);